### ISSUE TITLE
Error Handling Login - Redirect issue

### ISSUE THREAD

**Issue by brunix** [magsol/garmin#4]
It seems there is an issue with the Redirect. It was working fine a week ago. See below the error:

Traceback (most recent call last):
  File "garmin_parser.py", line 126, in <module>
    download_files_for_user(username, password, output)
  File "garmin_parser.py", line 88, in download_files_for_user
    login(agent, username, password)
  File "garmin_parser.py", line 34, in login
    agent.open(REDIRECT)
  File "build/bdist.macosx-10.10-intel/egg/mechanize/_mechanize.py", line 203, in open
  File "build/bdist.macosx-10.10-intel/egg/mechanize/_mechanize.py", line 255, in _mech_open
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by magsol** [comment]
I'm looking into the problem; they've really changed the login process. I'm having a hard time tracking down the exact problem, but from what I can tell it looks like they've added a `service_token` to the authentication process. Trying to figure out where that's generated and if I can append it to the existing URLs.

This will probably take a few more days.

**Comment by brunix** [comment]
I was reading this change.

https://github.com/wederbrand/workout-exchange/blob/master/garmin_connect/download_all.rb

I'm trying to apply the changes to see if I can manage to fix it. If I make progress I'll let you know.

**Comment by magsol** [comment]
Yes! That's precisely what needs to be implemented. I can work on it as well if you'd prefer.

**Comment by brunix** [comment]
If you could, it would be terrific! I'm more proficient in PHP than Ruby, indeed I was trying to translate it to PHP.

**Comment by magsol** [comment]
Got it working. Currently tidying up my fixes and will commit shortly.

**Comment by magsol** [comment]
This works for me again. Closing the ticket unless anyone else is still having problems.

**Comment by brunix** [comment]
Thanks Magsol! it works great!
