### ISSUE TITLE
Extract files by date for easier searching and sorting

### ISSUE THREAD

**Issue by AngelaKru** [magsol/garmin#5]
After downloading my 800+ runs, I realised that the filenames were all by activityId, which is meaningless when trying to search and sort. I tweaked my local copy around line 119 to the following to save the file by activity date and it worked a treat - I now have files named by activity date, and I'll work on a tweak when I have a moment to create subfolders to store by year and month for even better arrangement:

            activityId = item['activity']['activityId']
            activityDate = item['activity']['activitySummary']['BeginTimestamp']['value'][:10]
            url = TCX % activityId
            file_name = '{}_{}.tcx'.format(activityDate, activityId)

**Comment by magsol** [comment]
This isn't a feature I'd have thought of; I figured sorting by timestamp (or any other metric) is something you could just do downstream. Even so, I think it's a nice way of organizing the files into some sort of "default" order; it makes as much sense as any other. Please feel free to submit a PR with your changes and I'll incorporate them. Thanks!

**Comment by AngelaKru** [comment]
Done :)

**Comment by magsol** [comment]
Merged! Thank you!
