### ISSUE TITLE
HTTP Error 403: request disallowed by robots.txt

### ISSUE THREAD

**Issue by magsol** [magsol/garmin#8]
The `download.py` script is failing on line 44, in `login`:

```python
# First establish contact with Garmin and decipher the local host.
page = agent.open(BASE_URL)
pattern = "\"\S+sso\.garmin\.com\S+\""
script_url = re.search(pattern, page.get_data()).group()[1:-1]
agent.open(script_url)  ### FAILS HERE
```

The `script_url` being parsed here: `https://sso.garmin.com/sso/js/gauth-widget.js?20130313`, which points to a GAuth javascript widget. From what I can tell, this is not going to help with the login process.

**Comment by mipapo** [comment]
add the agent line to the def login worked for me:
def login(agent, username, password):
    global BASE_URL, GAUTH, REDIRECT, SSO, CSS
```
    # First establish contact with Garmin and decipher the local host.
    page = agent.open(BASE_URL)
    agent.set_handle_robots(False)   # no robots
    agent.set_handle_refresh(False)  # can sometimes hang without this
```

**Comment by magsol** [comment]
Fix works, thank you @mipapo!
